apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kafkausers.kafka.lrolaz.io
spec:
  group: kafka.lrolaz.io
  names:
    kind: KafkaUser
    listKind: KafkaUserList
    plural: kafkausers
    singular: kafkauser
  scope: Namespaced
  version: v1alpha1
