apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-topic-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-topic-operator
  template:
    metadata:
      labels:
        name: kafka-topic-operator
    spec:
      serviceAccountName: kafka-topic-operator
      containers:
        - name: kafka-topic-operator
          # Replace this with the built image name
          image: eu.gcr.io/kube-kafka-labo/kafka-topic-operator
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - kafka-topic-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kafka-topic-operator"
